import * as T from 'three';
import {RoadNetwork,Road,roadHeight} from '../world/RoadNetwork';
import {VehiclePhysics} from '../physics/VehiclePhysics';
import {wetness} from '../core/Weather';
export class CornerGuide{
 root=new T.Group();readonly markers:T.Mesh[]=[];visible=false;recommended=0;distance=0;brake=false;direction=0;private readonly a=new T.Vector3();private readonly b=new T.Vector3();
 constructor(private roads:RoadNetwork){const g=new T.ConeGeometry(.22,.6,8),m=new T.MeshBasicMaterial({color:'#ffda85'});for(let i=0;i<6;i++){const mesh=new T.Mesh(g,m);this.markers.push(mesh);this.root.add(mesh);}this.root.visible=false;}
 update(car:VehiclePhysics,active:boolean,route?:Road){this.visible=false;this.root.visible=false;if(!active||car.reverse||car.speed<5||car.contacts<2)return;const hit=this.roads.nearest(car.position.x,car.position.z,false,route),road=hit.road,sign=car.forward.dot(hit.sample.t)>=0?1:-1,start=hit.sample.d,look=Math.min(240,Math.max(70,car.speed*5));let strongest=0,where=0,turn=0;const wet=wetness(car.settings),grip=car.tune.dry*(1-wet)+car.tune.wet*car.traits.wet*wet,lateral=Math.min(11,6.8*car.spec.handling*grip*(1-wet*.4));for(let d=24;d<=look;d+=12){if(!road.closed&&(start+sign*d<20||start+sign*d>road.length-20))break;const before=this.roads.at(road,start+sign*(d-12)),after=this.roads.at(road,start+sign*(d+12));this.a.copy(before.t).setY(0).normalize();this.b.copy(after.t).setY(0).normalize();const angle=Math.acos(T.MathUtils.clamp(this.a.dot(this.b),-1,1)),curvature=angle/24;if(curvature>strongest){strongest=curvature;where=d;turn=Math.sign(this.a.x*this.b.z-this.a.z*this.b.x)*sign;}}
 if(strongest<.003)return;const safe=Math.min(55,Math.sqrt(lateral/strongest)),decel=5.8*car.tune.brakeForce*car.traits.brakes*(1-wetness(car.settings)*.25),braking=Math.max(0,(car.speed*car.speed-safe*safe)/(2*decel));this.recommended=Math.round(safe*3.6/5)*5;this.distance=Math.round(where);this.direction=turn;this.brake=braking+car.speed*.7>=where&&car.speed>safe+1;this.visible=where<car.speed*5+35;this.root.visible=this.visible&&car.settings.cornerGuide==='markers';if(this.root.visible)for(let i=0;i<6;i++){const s=this.roads.at(road,start+sign*Math.min(where,Math.max(12,where-braking)+(i>>1)*12)),side=i%2?1:-1,o=side*(road.width/2-.8),m=this.markers[i];m.position.set(s.p.x+s.r.x*o,roadHeight(s,o)+.4,s.p.z+s.r.z*o);} }
}
