import * as T from 'three';
import {RoadNetwork,Road,roadHeight} from './RoadNetwork';
type V={x:number;y:number;z:number;u:number;v:number};
type Face={road:Road;order:number;p:V[];minX:number;maxX:number;minZ:number;maxZ:number;sx:number;sz:number;b:number};
const cross=(a:V,b:V,p:V)=>(b.x-a.x)*(p.z-a.z)-(b.z-a.z)*(p.x-a.x);
function half(poly:V[],a:V,b:V,inside:boolean):V[]{const out:V[]=[];for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length],cp=cross(a,b,p),cq=cross(a,b,q),ip=inside?cp>=-1e-8:cp<=1e-8,iq=inside?cq>=-1e-8:cq<=1e-8;if(ip)out.push(p);if(ip!==iq){const f=cp/(cp-cq);out.push({x:p.x+(q.x-p.x)*f,y:p.y+(q.y-p.y)*f,z:p.z+(q.z-p.z)*f,u:p.u+(q.u-p.u)*f,v:p.v+(q.v-p.v)*f});}}return out;}
/** Subtract a convex pavement face. All resulting fragments retain their original grade/UVs. */
function subtract(poly:V[],clip:V[]):V[][]{const pieces:V[][]=[];let remain=poly;for(let i=0;i<3&&remain.length>=3;i++){const a=clip[i],b=clip[(i+1)%3],outside=half(remain,a,b,false);if(outside.length>=3)pieces.push(outside);remain=half(remain,a,b,true);}return pieces;}
export class PavementUnion{
 private cells=new Map<string,Face[]>();private order=new Map<Road,number>();
 constructor(roads:RoadNetwork){roads.roads.forEach((road,order)=>{this.order.set(road,order);for(let i=0;i<road.samples.length-1;i++){const a=road.samples[i],b=road.samples[i+1],point=(s:typeof a,o:number):V=>({x:s.p.x+s.r.x*o,y:roadHeight(s,o),z:s.p.z+s.r.z*o,u:0,v:0}),al=point(a,-road.width/2),ar=point(a,road.width/2),bl=point(b,-road.width/2),br=point(b,road.width/2);this.add(road,order,[al,ar,bl]);this.add(road,order,[ar,br,bl]);}});}
 private add(road:Road,order:number,p:V[]){if(cross(p[0],p[1],p[2])<0)[p[1],p[2]]=[p[2],p[1]];const a=p[0],b=p[1],c=p[2],det=cross(a,b,c);if(det<1e-9)return;const sx=((b.y-a.y)*(c.z-a.z)-(c.y-a.y)*(b.z-a.z))/det,sz=((b.x-a.x)*(c.y-a.y)-(c.x-a.x)*(b.y-a.y))/det;const f:Face={road,order,p,minX:Math.min(...p.map(v=>v.x)),maxX:Math.max(...p.map(v=>v.x)),minZ:Math.min(...p.map(v=>v.z)),maxZ:Math.max(...p.map(v=>v.z)),sx,sz,b:a.y-sx*a.x-sz*a.z};for(let z=Math.floor(f.minZ/64);z<=Math.floor(f.maxZ/64);z++)for(let x=Math.floor(f.minX/64);x<=Math.floor(f.maxX/64);x++){const key=x+','+z,list=this.cells.get(key)||[];list.push(f);this.cells.set(key,list);}}
 trim(g:T.BufferGeometry,road:Road,pavement=false){const p=g.getAttribute('position'),uv=g.getAttribute('uv'),idx=g.index!,positions:number[]=[],coords:number[]=[];for(let i=0;i<idx.count;i+=3){const poly:V[]=[];for(let k=0;k<3;k++){const n=idx.getX(i+k);poly.push({x:p.getX(n),y:p.getY(n),z:p.getZ(n),u:uv.getX(n),v:uv.getY(n)});}const minX=Math.min(...poly.map(v=>v.x)),maxX=Math.max(...poly.map(v=>v.x)),minZ=Math.min(...poly.map(v=>v.z)),maxZ=Math.max(...poly.map(v=>v.z)),faces=new Set<Face>();for(let z=Math.floor(minZ/64);z<=Math.floor(maxZ/64);z++)for(let x=Math.floor(minX/64);x<=Math.floor(maxX/64);x++)for(const f of this.cells.get(x+','+z)||[])if(f.road!==road&&(!pavement||f.order<this.order.get(road)!)&&f.maxX>=minX&&f.minX<=maxX&&f.maxZ>=minZ&&f.minZ<=maxZ)faces.add(f);
 let pieces=[poly];for(const f of faces){const next:V[][]=[];for(const piece of pieces){const overlap=half(half(half(piece,f.p[0],f.p[1],true),f.p[1],f.p[2],true),f.p[2],f.p[0],true);if(overlap.length<3||!overlap.some(v=>Math.abs(v.y-(f.sx*v.x+f.sz*v.z+f.b))<1)){next.push(piece);continue;}next.push(...subtract(piece,f.p));}pieces=next;if(!pieces.length)break;}
 for(const piece of pieces)for(let k=1;k<piece.length-1;k++){if(Math.abs(cross(piece[0],piece[k],piece[k+1]))<1e-7)continue;for(const v of [piece[0],piece[k],piece[k+1]]){positions.push(v.x,v.y,v.z);coords.push(v.u,v.v);}}}
 const result=new T.BufferGeometry();result.setAttribute('position',new T.Float32BufferAttribute(positions,3));result.setAttribute('uv',new T.Float32BufferAttribute(coords,2));result.computeVertexNormals();g.dispose();return result;}
}
