import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DriverAvatar,driverFit,loadRacerData} from '../src/player/DriverAvatar';import {CARS,isBike} from '../src/vehicles/CarCatalog';import {makeCar,CarVisual} from '../src/vehicles/CarModel';import {makeVehicle} from '../src/vehicles/VehicleModels';import {createImportedVehicle} from '../src/vehicles/ImportedVehicles';import {PhysicsWorld,VehiclePhysics,R} from '../src/physics/VehiclePhysics';import {OnFootPlayer} from '../src/player/OnFootPlayer';import {RoadNetwork} from '../src/world/RoadNetwork';import {defaults} from '../src/core/SaveManager';import {validPose} from '../src/multiplayer/Protocol';import {RemoteVehicle} from '../src/multiplayer/RemoteVehicle';
(globalThis as any).self=globalThis;(globalThis as any).createImageBitmap=async()=>({width:1024,height:1024,close(){}});(globalThis as any).ProgressEvent=class{constructor(type:string,init:any){Object.assign(this,{type,...init})}};
async function model(path:string){const b=await readFile(new URL('../assets/'+path,import.meta.url));return new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');}
const ready=(async()=>({racer:await model('characters/RACER.glb'),bike:await model('cars/MOTORCYCLE.glb'),supercar:await model('cars/REVUELTO.glb')}))();
test('uploaded model is external, compact, rigged and retains idle/walk animation with bounded textures',async()=>{
 const {racer}=await ready,b=await readFile(new URL('../assets/characters/RACER.glb',import.meta.url)),j=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)).toString());assert.ok(b.length<4_000_000);assert.deepEqual(racer.animations.map(a=>a.name),['Idle','Walking']);assert.equal(j.skins[0].joints.length,66);assert.equal(j.meshes.length,8);assert.equal(j.images.length,12);assert.ok(j.images.every((i:any)=>i.mimeType==='image/jpeg'));
 const avatar=new DriverAvatar(racer),box=new T.Box3().setFromObject(avatar.root,true);assert.ok(Math.abs(box.max.y-box.min.y-1.78)<.001);assert.ok(Math.abs(box.min.y)<.001);assert.equal(avatar.bones.length,66);
});
test('one avatar transfers through every seat and walking state; legacy riders stay hidden and poses fit roofs/contact points',async()=>{
 const loaded=await ready,avatar=new DriverAvatar(await model('characters/RACER.glb')),scene=new T.Group(),foot=new T.Group();scene.add(foot);const uuid=avatar.root.uuid;let transitions=0;
 for(const spec of CARS){const car=isBike(spec)?createImportedVehicle(loaded.bike.scene,spec):spec.kit==='supercar'?createImportedVehicle(loaded.supercar.scene,spec):['vanta','kestrel','apex'].includes(spec.id)?makeCar(false):makeVehicle(spec);scene.add(car.root);avatar.occupy(car,spec);const fit=driverFit(spec),hip=car.body.worldToLocal(avatar.bone('Joints_01').getWorldPosition(new T.Vector3()));assert.ok(hip.distanceTo(new T.Vector3(...fit.hip))<.0001,spec.id+' seat');
  const box=new T.Box3().setFromObject(avatar.root,true);if(['vanta','kestrel','apex'].includes(spec.id))assert.ok(box.max.y<1.24,spec.id+' helmet roof');if(spec.kit==='supercar')assert.ok(box.max.y<1.13,'supercar helmet roof');
  for(const side of [-1,1]){const left=side<0,wrist=car.body.worldToLocal(avatar.bone(left?'Joints_10_011':'Joints_34_035').getWorldPosition(new T.Vector3())),target=new T.Vector3((isBike(spec)?0:fit.hip[0])+side*fit.hand[0],fit.hand[1],fit.hand[2]);assert.ok(wrist.distanceTo(target)<.045,spec.id+' hands '+wrist.distanceTo(target));if(isBike(spec)){const ankle=car.body.worldToLocal(avatar.bone(left?'Joints_57_057':'Joints_62_062').getWorldPosition(new T.Vector3()));assert.ok(ankle.distanceTo(new T.Vector3(side*fit.foot[0],fit.foot[1],fit.foot[2]))<.025,'bike feet '+ankle.toArray());}}
  if(car.occupant)assert.equal(car.occupant.visible,false);
  car.root.position.set(20,24,280);car.root.rotation.set(.03,.7,-.02);
  for(let n=0;n<8;n++){avatar.onFoot(foot);assert.equal(avatar.root.parent,foot);assert.equal(car.body.getObjectsByProperty('name','PLAYER_AVATAR').length,0);assert.equal(scene.getObjectsByProperty('name','PLAYER_AVATAR').length,1);foot.position.x+=.075;avatar.update(1/60);avatar.returnToSeat();assert.equal(avatar.root.parent,car.body);assert.equal(foot.children.length,0);assert.equal(avatar.root.uuid,uuid);const seated=car.body.worldToLocal(avatar.bone('Joints_01').getWorldPosition(new T.Vector3()));assert.ok(seated.distanceTo(new T.Vector3(...fit.hip))<.0001,spec.id+' transformed seat');transitions++;}
  scene.remove(car.root);
 }
 assert.equal(transitions,64);
});
test('real exit/enter parks each vehicle and reuses one character visual and Rapier capsule with no residual seated body',async()=>{
 const physics=await new PhysicsWorld().init();physics.world.timestep=1/60;physics.box(0,-.1,0,100,.2,100);const roads=new RoadNetwork(),car=new VehiclePhysics(physics,roads,{...defaults}),avatar=new DriverAvatar(await model('characters/RACER.glb')),foot=new OnFootPlayer(physics,avatar),scene=new T.Group();scene.add(foot.root);const loaded=await ready,handle=foot.body.handle,bodies=physics.world.bodies.len();
 try{for(const spec of CARS){car.spec=spec;car.setPosition(0,.7,0,0);const visual=isBike(spec)?createImportedVehicle(loaded.bike.scene,spec):makeVehicle(spec);scene.add(visual.root);avatar.occupy(visual,spec);for(let i=0;i<100;i++){car.preStep({throttle:0,brake:1,steer:0,handbrake:false,up:false,down:false},1/60);physics.world.step();car.postStep(1/60);}assert.ok(foot.exit(car),spec.id);assert.equal(car.body.bodyType(),R.RigidBodyType.Fixed);assert.equal(avatar.root.parent,foot.root);assert.equal(visual.body.getObjectsByProperty('name','PLAYER_AVATAR').length,0);assert.equal(scene.getObjectsByProperty('name','PLAYER_AVATAR').length,1);for(let i=0;i<12;i++){foot.preStep({forward:1,right:0},0,1/60);physics.world.step();foot.postStep();foot.render(1);avatar.update(1/60);}assert.ok(foot.position.y>.8);assert.ok(foot.enter(car));assert.equal(avatar.root.parent,visual.body);assert.equal(foot.root.children.length,0);assert.equal(foot.body.handle,handle);assert.equal(physics.world.bodies.len(),bodies);scene.remove(visual.root);}}
 finally{physics.world.free();}
});
test('walking uses authored bone animation but never adds independent root movement',async()=>{
 const avatar=new DriverAvatar(await model('characters/RACER.glb')),foot=new T.Group();avatar.onFoot(foot);const position=avatar.root.position.clone(),leg=avatar.bone('Joints_56_056').quaternion.clone();for(let i=0;i<30;i++){foot.position.z-=.06;avatar.update(1/60);}assert.ok(leg.angleTo(avatar.bone('Joints_56_056').quaternion)>.1);assert.ok(avatar.root.position.distanceTo(position)<1e-10);assert.equal(avatar.root.parent,foot);assert.ok(Number.isFinite(new T.Box3().setFromObject(avatar.root,true).max.y));
});
test('peer pose occupancy is validated and removes the stationary remote rider when the player exits',()=>{
 const pose={t:'state',seq:1,car:'pulse',paint:'#ffffff',active:true,occupied:false,p:[0,.6,0],q:[0,0,0,1],steer:0,spin:0,lean:0,pitch:0,brake:0,race:'',progress:0,finished:false,time:0};assert.ok(validPose(pose));assert.equal(validPose({...pose,occupied:'false'}),false);const remote=new RemoteVehicle();remote.receive(pose as any,1000);remote.update(1010,true,new T.Vector3());const rider=remote.root.getObjectByName('motorcycle-rider')!;assert.equal(rider.visible,false);remote.receive({...pose,seq:2,occupied:true} as any,1050);remote.update(1060,true,new T.Vector3());assert.equal(rider.visible,true);
});

test('bounded startup transfers reconstruct the exact uploaded model and reject damaged or failed downloads',async()=>{
 const original=await readFile(new URL('../assets/characters/RACER.glb',import.meta.url)),urls=Array.from({length:30},(_,i)=>String(i));let active=0,maxActive=0;
 const fetcher=async(url:any)=>{active++;maxActive=Math.max(maxActive,active);await new Promise(resolve=>setTimeout(resolve,1));active--;const i=Number(url);return new Response(original.subarray(i*120000,Math.min((i+1)*120000,original.length)));};
 const result=await loadRacerData(urls,fetcher as any,()=>{});assert.deepEqual(Buffer.from(result),original);assert.ok(maxActive<=6);
 await assert.rejects(loadRacerData(urls,(async()=>new Response('',{status:503})) as any),/download failed/);
 await assert.rejects(loadRacerData(urls,(async()=>new Response(new Uint8Array(1))) as any),/Incomplete/);
});
