import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {RoadNetwork,Road} from '../src/world/RoadNetwork';import {roadRibbon} from '../src/world/roadGeometry';import {PavementUnion} from '../src/world/PavementUnion';
import {validateSetup,setupTune,axleShare} from '../src/vehicles/DriverSetup';import {BASE_TUNE,STOCK} from '../src/vehicles/UpgradeCatalog';import {SaveManager,defaults} from '../src/core/SaveManager';import {PhysicsWorld,VehiclePhysics} from '../src/physics/VehiclePhysics';import {CornerGuide} from '../src/vehicles/CornerGuide';import {wetness} from '../src/core/Weather';import {FrameDiagnostics} from '../src/core/FrameDiagnostics';import {inviteURL,inviteCode,cleanName,connectionQuality} from '../src/multiplayer/Invites';import {routePreview} from '../src/world/RoutePreview';import {cleanPlate} from '../src/vehicles/CosmeticCatalog';
function road(name:string,coords:number[][],width=8):Road{const points=coords.map(p=>new T.Vector3(...p as [number,number,number]));const samples=points.map((p,i)=>{const t=points[Math.min(i+1,points.length-1)].clone().sub(points[Math.max(0,i-1)]).normalize();return {p,t,r:new T.Vector3(-t.z,0,t.x).normalize(),d:i*20};});return {name,width,closed:false,samples,length:(samples.length-1)*20,curve:new T.CatmullRomCurve3(points)};}
function area(g:T.BufferGeometry){const p=g.getAttribute('position'),idx=g.index;let n=0;for(let i=0;i<(idx?.count||p.count);i+=3){const a=idx?idx.getX(i):i,b=idx?idx.getX(i+1):i+1,c=idx?idx.getX(i+2):i+2;n+=Math.abs((p.getX(b)-p.getX(a))*(p.getZ(c)-p.getZ(a))-(p.getZ(b)-p.getZ(a))*(p.getX(c)-p.getX(a)))/2;}return n;}
function contains(g:T.BufferGeometry,x:number,z:number){const p=g.getAttribute('position');for(let i=0;i<p.count;i+=3){let positive=false,negative=false;for(let k=0;k<3;k++){const a=i+k,b=i+(k+1)%3,v=(p.getX(b)-p.getX(a))*(z-p.getZ(a))-(p.getZ(b)-p.getZ(a))*(x-p.getX(a));positive ||= v>1e-7;negative ||= v< -1e-7;}if(!(positive&&negative))return true;}return false;}
test('intersection pavement is an actual geometric union, with no duplicate asphalt or shoulders crossing the other road',()=>{const a=road('a',[[-20,0,0],[0,0,0],[20,0,0]]),b=road('b',[[0,0,-20],[0,0,0],[0,0,20]]),network={roads:[a,b]} as RoadNetwork,union=new PavementUnion(network),ag=union.trim(roadRibbon(a,0,2,-4,4),a,true),bg=union.trim(roadRibbon(b,0,2,-4,4),b,true),shoulder=union.trim(roadRibbon(b,0,2,4,6),b);assert.ok(Math.abs(area(ag)+area(bg)-(320+320-64))<.001);assert.equal(contains(ag,.13,.21),true);assert.equal(contains(bg,.13,.21),false);assert.equal(contains(shoulder,-5,.2),false);assert.ok([...bg.getAttribute('uv').array].every(Number.isFinite));for(const g of [ag,bg,shoulder])g.dispose();});
test('height-separated overpasses remain intact and clipping preserves sloped branch UVs and grade',()=>{const a=road('ground',[[-20,0,0],[0,0,0],[20,0,0]]),b=road('bridge',[[0,8,-20],[0,8,0],[0,8,20]]),u=new PavementUnion({roads:[a,b]} as RoadNetwork),g=u.trim(roadRibbon(b,0,2,-4,4),b,true);assert.equal(area(g),320);assert.ok([...g.getAttribute('position').array].filter((_,i)=>i%3===1).every(y=>y===8));g.dispose();});
test('driver setups clamp malicious save data, retain upgrade defaults and redistribute axle torque without creating force',()=>{const v=validateSetup({brakeBias:9,steering:-9,differential:2,spring:NaN});assert.deepEqual(v,{brakeBias:.75,steering:.6,differential:1,spring:1});assert.equal(setupTune({...BASE_TUNE,frontBias:.65},validateSetup(null)).frontBias,.65);assert.equal(setupTune(BASE_TUNE,{...validateSetup(null),spring:1.25}).stiffness,55);assert.equal(axleShare(true,true,1),.5);assert.equal(axleShare(true,false,0),.5);assert.equal(axleShare(true,false,1),.85);assert.ok(Math.abs(axleShare(true,false,1)+axleShare(false,true,1)-1)<1e-8);});
test('actual vehicle controller applies brake bias, spring stiffness and steering sensitivity',async()=>{const physics=await new PhysicsWorld().init(),roads=new RoadNetwork(),car=new VehiclePhysics(physics,roads,{...defaults});try{car.applyLoadout(STOCK,{brakeBias:.7,steering:1.4,differential:1,spring:1.25});car.body.setLinvel({x:0,y:0,z:-20},true);car.preStep({throttle:0,brake:1,steer:1,handbrake:false,up:false,down:false},1/60);assert.equal(car.tune.stiffness,55);assert.equal(car.tune.frontBias,.7);assert.ok(car.controller.wheelBrake(0)!>car.controller.wheelBrake(2)!*2);assert.ok(car.steering>0);car.applyLoadout(STOCK);assert.equal(car.setup.steering,1);assert.equal(car.tune.stiffness,44);}finally{physics.world.free();}});
test('corner guidance predicts a slower wet entry, braking demand, disabled state and reusable marker pool',async()=>{const physics=await new PhysicsWorld().init(),roads=new RoadNetwork(),car=new VehiclePhysics(physics,roads,{...defaults}),guide=new CornerGuide(roads),r=roads.roads.find(r=>r.name==='HIGHLAND SWITCHBACKS')!;try{let found=false;for(const s of r.samples){car.teleport(r,s.d,0);car.speed=60;car.contacts=4;guide.update(car,true,r);if(guide.visible){found=true;const dry=guide.recommended;car.settings.weather='rain';car.settings.rainIntensity=1;guide.update(car,true,r);assert.ok(guide.recommended<dry);assert.equal(guide.brake,true);break;}}assert.ok(found);assert.equal(guide.markers.length,6);guide.update(car,false);assert.equal(guide.visible,false);assert.equal(guide.root.visible,false);}finally{physics.world.free();}});
test('progress, custom setup, cosmetic unlocks and dry/wet records persist independently under the existing save key',()=>{const map=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(k:string)=>map.get(k)||null,setItem:(k:string,v:string)=>map.set(k,v)}});const save=new SaveManager();save.coins=300;save.best=200;save.bestByLaps[1]=200;save.setSetup('steering',1.2);save.setPlate('<ab# 123>');assert.equal(save.buyLivery('twin'),'equipped');assert.equal(save.coins,120);assert.equal(save.buyLivery('race'),'insufficient');save.recordRoute('coast',120);save.recordRoute('coast',170,'wet');save.recordLap(220,'vanta',1,false,false,'wet');save.settings.rainIntensity=.2;save.save();const loaded=new SaveManager();assert.equal(loaded.best,200);assert.equal(loaded.routeBests.coast,120);assert.equal(loaded.wetRouteBests.coast,170);assert.equal(loaded.lapRecords[0].condition,'wet');assert.equal(loaded.setup.steering,1.2);assert.equal(loaded.liveries.vanta,'twin');assert.equal(loaded.plates.vanta,'AB 123');assert.equal(loaded.settings.rainIntensity,.2);assert.equal(loaded.coins,120);assert.equal(cleanPlate(null),'REDLINE');});
test('invites preserve deployment paths, replace old codes, reject malformed input and sanitize names',()=>{const url=inviteURL('https://example.test/redline-horizon/?room=OLDX&x=1#map','ABCD');assert.equal(new URL(url).pathname,'/redline-horizon/');assert.equal(inviteCode(url),'ABCD');assert.equal(new URL(url).searchParams.get('x'),'1');assert.equal(inviteCode('https://example.test/?room=ab12'),'');assert.equal(inviteCode('invalid'),'');assert.equal(cleanName('<Pilot>\n'), 'Pilot');assert.equal(connectionQuality(40),'Good');assert.equal(connectionQuality(400),'Slow');});
test('diagnostics use bounded sample buffers and weather/elevation previews stay finite',()=>{const d=new FrameDiagnostics();for(let i=0;i<300;i++)d.record(16,3,4,9);assert.equal(d.count,120);assert.equal(d.frame.length,120);assert.deepEqual(d.averages(),{frame:16,physics:3,render:4,cpu:9});assert.equal(wetness({...defaults,weather:'clear'}),0);assert.equal(wetness({...defaults,weather:'rain',rainIntensity:1}),1);const info=routePreview(new RoadNetwork().main);assert.ok(info.gain>0&&info.max>info.min&&info.length>19000);});

test('all world road ribbons retain visible lane coverage without coplanar intersection duplicates',()=>{
 const roads=new RoadNetwork(),union=new PavementUnion(roads),grid=new Map<string,{road:Road;p:T.BufferAttribute|T.InterleavedBufferAttribute;i:number}[]>(),geometries:T.BufferGeometry[]=[];
 for(const road of roads.roads){const g=union.trim(roadRibbon(road,0,road.samples.length-1,-road.width/2,road.width/2),road,true);geometries.push(g);const p=g.getAttribute('position');for(let i=0;i<p.count;i+=3){const minX=Math.min(p.getX(i),p.getX(i+1),p.getX(i+2)),maxX=Math.max(p.getX(i),p.getX(i+1),p.getX(i+2)),minZ=Math.min(p.getZ(i),p.getZ(i+1),p.getZ(i+2)),maxZ=Math.max(p.getZ(i),p.getZ(i+1),p.getZ(i+2));for(let x=Math.floor(minX/64);x<=Math.floor(maxX/64);x++)for(let z=Math.floor(minZ/64);z<=Math.floor(maxZ/64);z++){const key=x+','+z,list=grid.get(key)||[];list.push({road,p,i});grid.set(key,list);}}}
 let checks=0;for(const road of roads.roads)for(let n=2;n<road.samples.length-2;n+=7){const a=road.samples[n],b=road.samples[n+1],f=.37;for(const offset of [-.22,.08,.27]){const o=offset*road.width,x=a.p.x+(b.p.x-a.p.x)*f+(a.r.x+(b.r.x-a.r.x)*f)*o,z=a.p.z+(b.p.z-a.p.z)*f+(a.r.z+(b.r.z-a.r.z)*f)*o,y=a.p.y+(b.p.y-a.p.y)*f+(Math.tan(a.bank||0)+(a.crossSlope||0))*o;const hits=new Map<Road,number>();for(const {road,p,i} of grid.get(Math.floor(x/64)+','+Math.floor(z/64))||[]){const ax=p.getX(i),az=p.getZ(i),bx=p.getX(i+1),bz=p.getZ(i+1),cx=p.getX(i+2),cz=p.getZ(i+2),det=(bx-ax)*(cz-az)-(bz-az)*(cx-ax),u=((x-ax)*(cz-az)-(z-az)*(cx-ax))/det,v=((bx-ax)*(z-az)-(bz-az)*(x-ax))/det;if(u>=-1e-5&&v>=-1e-5&&u+v<=1+1e-5){const h=p.getY(i)*(1-u-v)+p.getY(i+1)*u+p.getY(i+2)*v;if(Math.abs(h-y)<1)hits.set(road,h);}}assert.ok(hits.size>0,`${road.name} missing visible pavement ${n} ${x},${z}`);assert.ok(hits.size<=1,`${road.name} duplicate pavement ${n}: ${[...hits.keys()].map(r=>r.name)}`);checks++;}}
 console.log({intersectionLaneChecks:checks,trimmedTriangles:geometries.reduce((n,g)=>n+g.getAttribute('position').count/3,0)});for(const g of geometries)g.dispose();
});

test('city building foundations reach the rendered terrain instead of floating above lowered road-support ground',async()=>{
 const {World}=await import('../src/world/World'),roads=new RoadNetwork(),physics=await new PhysicsWorld().init(),world=new World(roads,physics,{...defaults});try{world.buildCity();const foundations=world.city.children.filter(o=>o.name==='Solid city foundation') as T.Mesh[];assert.ok(foundations.length>5);for(const foot of foundations){foot.geometry.computeBoundingBox();const box=foot.geometry.boundingBox!,bottom=box.min.y+foot.position.y,top=box.max.y+foot.position.y;assert.ok(bottom<world.terrainSampler.groundHeight(foot.position.x,foot.position.z));assert.ok(top>=world.terrainSampler.groundHeight(foot.position.x,foot.position.z));}}finally{physics.world.free();}
});

test('autopilot compensates driver steering sensitivity so its physical wheel angle stays consistent',async()=>{
 const {Autopilot}=await import('../src/vehicles/Autopilot'),physics=await new PhysicsWorld().init(),roads=new RoadNetwork(),car=new VehiclePhysics(physics,roads,{...defaults}),manual={throttle:0,brake:0,steer:0,handbrake:false,up:false,down:false};try{car.teleport(roads.main,1100,3);car.speed=8;car.slip=0;const pilot=new Autopilot(roads);pilot.toggle(car);const stock=pilot.controls(car,80,'steering',manual,{},1).steer;car.applyLoadout(STOCK,{...validateSetup(null),steering:1.4});const tuned=new Autopilot(roads);tuned.toggle(car);const result=tuned.controls(car,80,'steering',manual,{},1).steer;assert.ok(Math.abs(stock)>.001);assert.ok(Math.abs(stock-result*1.4)<.0001);}finally{physics.world.free();}
});
